initial commit;
AleksandrPok/hibernate-practice pull request #5
Opened 2021-02-05 08:55 UTC by AleksandrPok

2021-02-05 10:02 UTC, Max-Pochepets approved these changes

2021-02-05 10:02 UTC, Max-Pochepets commented on src/main/java/cinema/dao/OrderDaoImpl.java
> +            throw new DataProcessException("Can't get user history: " + user, e);
```suggestion
            throw new DataProcessException("Can't get user's orders history: " + user, e);
```

2021-02-05 10:02 UTC, Max-Pochepets commented on src/main/java/cinema/service/OrderServiceImpl.java
> +        shoppingCartService.clear(shoppingCart);
if it is like this - 26 line is redundant. Shopping cart's tickets getting cleared on 23 line. make a copy of tickets list and it'll be ok

2021-02-05 10:08 UTC, dmytro-hryhoruk requested changes
Fix @Max-Pochepets comments

2021-02-06 13:55 UTC, dmytro-hryhoruk approved these changes

2021-02-08 05:36 UTC, merged